### ISSUE TITLE
TypeError: Invalid character in header field name

### ISSUE THREAD

**Issue by tommedema** [wessberg/Polyfiller#13]
I cannot reproduce this but I got this error from one of my users in Sentry

Does this make sense to you?

<img width="1129" alt="Screen Shot 2020-04-02 at 12 24 49 PM" src="https://user-images.githubusercontent.com/331833/78293141-f5948580-74dc-11ea-80c7-c4e4883444a9.png">

```
TypeError: Invalid character in header field name
--
arguments | [{"message":"Invalid character in header field name","name":"TypeError","stack":"TypeError: Invalid character in header field name\n    at normalizeName (https://polyfill.app/api/polyfill?features=url,fetch,pointer-event,scroll-behavior:1:75432)\n    at Headers.append (https://polyfill.app/api/polyfill?features=url,fetch,pointer-event,scroll-behavior:1:76247)\n    at Headers.<anonymous> (https://polyfill.app/api/polyfill?features=url,fetch,pointer-event,scroll-behavior:1:76159)\n    at Array.forEach (<anonymous>)\n    at new Headers (https://polyfill.app/api/polyfill?features=url,fetch,pointer-event,scroll-behavior:1:76131)\n    at new Request (https://polyfill.app/api/polyfill?features=url,fetch,pointer-event,scroll-behavior:1:81348)\n    at https://polyfill.app/api/polyfill?features=url,fetch,pointer-event,scroll-behavior:1:83734\n    at new Promise (<anonymous>)\n    at fetch (https://polyfill.app/api/polyfill?features=url,fetch,pointer-event,scroll-behavior:1:83685)\n    at https://app.usebubbles.com/static/js/2.fafbee11.chunk.js:1:914256\n    at https://app.usebubbles.com/static/js/main.79af2afc.chunk.js:1:175882\n    at u (https://app.usebubbles.com/static/js/2.fafbee11.chunk.js:1:471028)\n    at Generator._invoke (https://app.usebubbles.com/static/js/2.fafbee11.chunk.js:1:470781)\n    at Generator.forEach.e.<computed> [as next] (https://app.usebubbles.com/static/js/2.fafbee11.chunk.js:1:471385)\n    at r (https://app.usebubbles.com/static/js/2.fafbee11.chunk.js:1:34154)\n    at s (https://app.usebubbles.com/static/js/2.fafbee11.chunk.js:1:34357)\n    at https://app.usebubbles.com/static/js/2.fafbee11.chunk.js:1:34416\n    at new Promise (<anonymous>)\n    at https://app.usebubbles.com/static/js/2.fafbee11.chunk.js:1:34297\n    at https://app.usebubbles.com/static/js/main.79af2afc.chunk.js:1:176085\n    at https://app.usebubbles.com/static/js/main.79af2afc.chunk.js:1:172971\n    at u (https://app.usebubbles.com/static/js/2.fafbee11.chunk.js:1:471028)\n    at Generator._invoke (https://app.usebubbles.com/static/js/2.fafbee11.chunk.js:1:470781)\n    at Gene..."}]
```

**Comment by wessberg** [comment]
I think what you're seeing here is simply an error related to trying to use an invalid character as part of the value for the request headers of a fetch request. The error is _reported_ from within the polyfill bundle as the error is thrown by the fetch polyfill, but based on the provided stack trace I wouldn't suspect a bug in the fetch polyfill. By the way, I'm working on sourcemap support which will make it easier to debug this kind of stuff.

**Comment by tommedema** [comment]
Hmm ok. I'm not really passing in any special headers so perhaps this is the user's chrome extension or something?

This is my fetch call

```javascript
fetch(endpoint, {
    method: 'post',
    headers: {
      "Accept": "application/json",
      "Content-type": "application/json"
    },
    body: JSON.stringify(bodyObj)
  })
```

**Comment by wessberg** [comment]
Sure, that can happen. Could maybe also be another library you are relying on that is sending a fetch request? In any case, what you posted here looks fine to me
