### ISSUE TITLE
Chrome 86 error

### ISSUE THREAD

**Issue by Anoesj** [wessberg/Polyfiller#22]
Hey there,

Thanks for making Polyfiller!

I'm using the following URL to polyfill `es`, `intl` (Dutch) and `fetch`: https://polyfill.app/api/polyfill?features=es,intl|locale=nl,fetch
However, this returns an error when using Chrome 86:
```
An Error occurred.
Code: 500
BrowserslistError

BrowserslistError: Unknown version 86 of chrome at Function.select (/app/node_modules/browserslist/index.js:1086:17) at /app/node_modules/browserslist/index.js:336:33 at Array.reduce () at resolve (/app/node_modules/browserslist/index.js:318:18) at browserslist (/app/node_modules/browserslist/index.js:443:21) at normalizeBrowserslist (/app/node_modules/@wessberg/browserslist-generator/dist/cjs/index.js:741:12) at generateBrowserslistFromUseragent (/app/node_modules/@wessberg/browserslist-generator/dist/cjs/index.js:1461:36) at Object.userAgentSupportsFeatures (/app/node_modules/@wessberg/browserslist-generator/dist/cjs/index.js:1501:35) at shouldIncludePolyfill (/app/dist/index.js:3456:102) at polyfillSet.forEach.polyfill (/app/dist/index.js:3491:13)

BrowserslistError: Unknown version 86 of chrome
```

Any idea what might be going on?

**Comment by wessberg** [comment]
This problem has been fixed and is now now!
